apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:cfWY2dU=,iv:kmYWZ3ZR5uLCqjnUCRqrYzc2sH8y4GNcZ2omwy4ZT24=,tag:IIgK7J0GTTtOQdeUdJp1gw==,type:str]
    admin-password: ENC[AES256_GCM,data:aXuNtGS/fQPdeYOrX8/TwXP0mHKTK6V+,iv:uLXdwXfkPcIFMEJvQEVEVSU4ADYX4Lfh0/FlJMuIHzo=,tag:0KaLpW3Qf1sQ0QfP5a/xwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTiswSmthTkFkZGNDYzhn
            aE11c0VFQnAxcURTTEhEbE0zVmlUUUUzMUNrCks0TWdkdVkxakVOZGI4TTlkbmJL
            VXEyUlVEdDc3cUlFUkJUd0RLME1YdjgKLS0tIEo4eS9qNll2QVlCaXRKSjYxQ3Vy
            dUFCYTJCeDZ5eCtYOVhrU2lkanhuUVUKNWxRfi1wjNqrnVmYYdzFfkMIMBC/7SCI
            uO6L2a0qnBflkXmzkM4n88ifLouG2qim38cEQkvCbtrWRekTrmdq6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQks1czhDQi82MUUvTU8x
            SnRIaUhuV3BTQVJGUk1SYVNmMDNQVTN6UEJBCkNMKys4YTR5QlpKbHp2eXF4K0NO
            L29WSDlsTDI3blZveG5xdkk1SkRaajgKLS0tIGhRRW12WjdFa29xSUQrdVV5Z29T
            TFNEblJuYlN1eGVsVEp6VkdBVzdUOEUKWBoAuVkp/QRIrCfVcGK6pCGrautu7SrP
            MFaeJ2hGs9gVoE9Q+gfUJDyRMQR7kE3uJm5hG0iJeV08ccJzXULScw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZnIrVitpLzNVNzhvUlRo
            eFlqd0gxKzZ3MlZVdGZXc1lwR1FqcG9ONWtRCkgranFWcVNCbkNhdzVaRXhsU3BB
            K09JbzBJTHY5OEpMOG15dVFEc2xIMncKLS0tIDI5a3dPS2JVU2xkUXM2dmRhU2k3
            TWhpNjlqU3dmT09uaFlHbjA4djhzYTQKz9638Bbh9/MwuvL+UOF+SUtTvFI/eifE
            1FWFBPATFehTG72QXcwhntGo7rvwDkO+H1F6nZ5zaorW2lQ5/wrtZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18c0ldwxzslhphke4gxaw2qgjdcpjp4d9dtzq8aew3sm7e383qpaq23607c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T14:20:39Z"
    mac: ENC[AES256_GCM,data:eYehXFIcmpASEuu5lOryS8XJATy4tH5xOTftn6LwSU1qEAE+P+uEZ6SUKpJBykqTRovItbxgk6GDPCmwI8g7X/6XSFpf+WDx2swht7iO5BPYRu6CL/xPCap/cZ7X/I22KAaDkSlKKUV912Kfc0vdgdJq1O6qZCfSPoYqnqZvwgU=,iv:8GfV5dXEhBF7b2qw5z4Qz5rkR82LAEpvP7PxEdceBNY=,tag:9HULadiKQbyPm/T7TJFkWA==,type:str]
    version: 3.13.3
