all:
  children:
    gateway:
      hosts:
        linode-gw:
          ansible_host: "{{ gateway_public_ip }}"
          wg_address: 10.100.0.1
    k8s_cluster:
      children:
        k8s_control_plane:
          hosts:
            node1: { ansible_host: 192.168.10.11, wg_address: 10.100.0.11 }
            node2: { ansible_host: 192.168.10.12, wg_address: 10.100.0.12 }
            node3: { ansible_host: 192.168.10.13, wg_address: 10.100.0.13 }
        k8s_workers:
          hosts:
            node4: { ansible_host: 192.168.10.14, wg_address: 10.100.0.14 }
            node5: { ansible_host: 192.168.10.15, wg_address: 10.100.0.15 }
            node6: { ansible_host: 192.168.10.16, wg_address: 10.100.0.16 }
