apiVersion: v1
kind: Secret
metadata:
    name: wings-config
    namespace: wings
type: Opaque
stringData:
    config.yml: ENC[AES256_GCM,data:7IvT4yUokPoEBtmI4HnMm8WOVvmvzTJCzn3wVs/9dSQ1/dg8axwO+3+kL28RZ7ZuhUxhgpvJGQm833tBINjXCtyAlq+XPKF14O3g7hafGGzFt7TczDNfSfkNkNYNUhi/eRSOC4i4EsZO32KlI61tNM78oDpoMMxPAr4zbBhiNcwepY7drSzfuK1kXf1IVYk8VkkBNlACG0hCTctpxhjC1Xi1EC9JDjpv4sTD9cAp+tK5d2Nj7tmGscuc8LHC1v+5AGL0+/PZyA9Qt4tbHPk+fDto7hT9d0jECVthacu5D3tqGYwaa5mvqo4qH3UhMajlZC9jdO5xrUrJiuaM7O/oRZ4bgZ8Fivs4M4ns5v5B4K10E5mzIUsprFFiGkMraktddiKl5yIbYy6R3qSIFqDi0X+2W0GV/Exeaad3IrjtMVyQCGlFLMOAqcbRZ+DpdOXrczNH0vLzR29jtE6rhx7X6JZLixPhQ5+OpzhDDIOMsx0NmT7Rpq52NEczBK3DytjEZtLS+gXWx+ZZ1Y3GVy3AHjoN4iiCRaKbgxsbLBgLBZqS7eORMJs5IbRrJrnPEHQmMSXfx07LMgodVP37J9rb0iRjfm22us99WbsRe9Z1+q2NYNQ2qPtXgaIag+Wl4L59rjCqH28E0mUYSNgSqzELKQrUQH84OyeohRWO6dLynA==,iv:rd80nOXnx00MLIH33Ioj3BH1gicEnsyse00GhwvlFkA=,tag:pQyI6/Nqc+psGndhaM3qvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTHhGN3BkaXJDeWhhd3dQ
            ZkJKOGZuOWFCS21NM2o3WHlwTHJxRXFXb0h3CkhYck1sa2xsaFg1MlFUMUUrYkZM
            cGNnc1Nrald4eXhCU3ltWkduMUZVN28KLS0tIFQ4SkVmMlBvYkxDSFB1SnlSVVVJ
            b3FFa2hNZVA1T2VGR0NRL0pWUUk5TFUKmLwtIyLKNhpw+WgT5HkO/r63S/bHN42D
            aSecdXtaw3orIimeJUJ6PNaENeeALCyOI+IneMI6h0GxKLEu58gdlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvY0JHMitURkRhZzE1STh6
            cUNMZzh0TDBjNzNMUExYSCtuUmE2ekMzQ2o0CnFZZ3VDTHdCcjU4MVJPUnVzUEdR
            cVdxc3Y2R1E0N0x6dGpyQkNLVkdQMWcKLS0tIFFKbHYzK0c1TGYvVnR2SGhFS1JH
            bmJhYWlMTGIxOTFRb2d0N1JwMWdCcFEKucVbNKuP1Ga1Ohm9ClMRziFidJxOXUVq
            Zqq6pJoPY6nA+HDhMKwz+8/7scC1VNxICidjraRRllMuzCVxp+uyfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcmRSWmI1eHFDZ0MyOWl3
            Z2tzU0xWb05WUlQvSDNkdHpsczdISmFCV1JRCjdHc3dXcERxaVlvRW5oeWowZGE3
            bW9EYzlUdEhzTWJYMVdRNG1nVG5qQmsKLS0tIHFDekp4NzIxVmlLWHFGZ2RRSUFN
            ZDJzV0xpS0REMjJ4WGRlWE01bHBnVFUKTguBriVmPT6p9+dv060B2BTKUFesQ5Xp
            W82HCOTFFUSHGSTnYAOnABsjBNFMt1oJesEXCiBwpyz6crdff/V08w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18c0ldwxzslhphke4gxaw2qgjdcpjp4d9dtzq8aew3sm7e383qpaq23607c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T07:56:33Z"
    mac: ENC[AES256_GCM,data:LwS5s2y3vG7P+L/tI68hdRE+l7HygjfjG8iciSckB6xH8yHH6pB/v9lg04H6TfKyzYH06P7z8c3riTRIjImK4N6uwTH/7ZWDtOcGU/50W8vkm2Fj1gO/BbEJ9rerB6PneqEF9hBHhz6o2wjpMaMM2UFpT5ZFBD/TPOCGsIQW1nA=,iv:5Fp816cgeZ4atkrsys3BZnAwhVD0Q2m61eqSxUHSpiI=,tag:yF4YiYBqcov3dsYOIt5HBg==,type:str]
    version: 3.13.3
