apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    opencode-go-api-key: ENC[AES256_GCM,data:Jn26nGeIGMy8GUUTIFn12uvmJmEOkSfsz1quDYcMvNzH4N72CgqgLpBVQrAN8P7I1LS82JMcPoS1tt8M5s0sp4vJjg==,iv:PjD/KVd+/No/6vl87l625LkQfspDDiHWc9xRnVS6xRM=,tag:G883qVNaGMSu7d7jjp1vag==,type:str]
    discord-bot-token: ENC[AES256_GCM,data:Ks46xq9S5IahQKh8YRey2A55JcqU7ZzsOevPYAvpRZAdnM7dd4l3QdCY1vYwMLsJxZSjUseYL49GVKljmYJa3T8BbxvXersA,iv:Eo+Wp/mZ2WeXAcM13cU747FJuo3gYHs+syJOJV1I+CM=,tag:ucL8Esel9NfW86l+RZ6igA==,type:str]
    keenable-api-key: ENC[AES256_GCM,data:ZLbWY/eWd/o22BalC0clNdu/UIs3VrPiulQN5Yqeaz3VSzbekklgef8GnRGGOX3XtWZsYC/JCmji9Gr5sYdCiYZTGxt9Wdw3sJhB1MlOmgM=,iv:bEo5zMqUOZ4ZYtsg0L4AQyHy4eN1TAOxSsda/XOGnfU=,tag:Y5+rfMwskUNwm8E7f4/pKw==,type:str]
    dashboard-username: ENC[AES256_GCM,data:tAOk9ti8,iv:usqLAhHTpAYu0v6kojqETLu5+Ai/V1Q3nzXzK3LwSEw=,tag:IDDEtOeMdRJymgu97qhLGA==,type:str]
    dashboard-password: ENC[AES256_GCM,data:GZ1lOBpQ,iv:azZvycbz72uVZ599SfrJgl3Lca2utiHzy/eNfZgolaQ=,tag:2tYqnviCYl2YBFh4lQdwQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOazUzbW0ycmtFakN0azE2
            WTFUdXdhSGJxOERVMW1qbzR1eHpSZW9MR3djCklYb1JnOHhuNVUrVkh1S3p4REJX
            YjJiRWYrcG5naCtZWG1JazZ6VWJqaGsKLS0tIEs5T3dBcHJyUFh6cVZPMlR6UXZx
            M0EreXZtL2h3OEJaWEh1d0JweG1NWk0KQ+vJ9GbI51G7skHeI1aIgcGdIS6Nv4Ms
            K59JaZsKhJeKV/16H6wU5Hy4tTvrqx/f2oRu30rJUNbW63p4H3t3rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSDBHK2x2RVhaZFBjbkdL
            eUJOZDhUcDUrWDM5T1hlMGJnVlRQYmFSbEE0CkVobXdVelEwSWppOVJRd0diUG5i
            Yjc3cDg1ZGhnSkhUMTlsL001V01LTEUKLS0tIE5qWVk1czNLcEtoL1kwdDFVbzFI
            SG5TWXZENU1SRDNPY0twanF0Q2poYXMKxGqdKmbJLJFjdeh0PcuSAd8NjRg0i9Qa
            q4cWSZWHY249hkjkSUjnzB0EKCegUt2keJ6/LFifi0Rj1Ukiq67vBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa2RMcldpWTNJSHJsOFVS
            SUJxdzIySHhDb1VjRUxNUnZMNjZOWG1IVG1vCmI1MkVvWFdQMFN1OGczdUpqU3Js
            VERxQ1gxMUc5ekU4KytyaGZ5QmRPcFkKLS0tIHFpdmJKMW1Pak9ZUzlhY2NxTmt2
            YUpVbXE3UXhSemxJTVJ1bU9mUHFhZ3MKd5n1HOC6WhRz5zMworC8Jw/4+ZwM+KbO
            Kg9rAfNZ9SUv94oHU2IFO++4cFErW7xqKxY+W5pTUvEO4rQEduBddQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18c0ldwxzslhphke4gxaw2qgjdcpjp4d9dtzq8aew3sm7e383qpaq23607c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T00:26:56Z"
    mac: ENC[AES256_GCM,data:JLMc5/pzEzDyVmN7e1oV+5d/Y2b1lcMbpxCfvb/6LaifXrvzyAwqu2Qiyp1wLhuT6Hkwop2eNp3EH1dAZPTRsEMRMvEUVPHaAP/wM/OT9XwKAKPTzMBqh4PK2XeZBg1Wd7Xp5HtpXBu7EIIUQ6o0ZWvKP80o67spQk7rX4uYH5Q=,iv:tbs0GX54HG5POATBbZE87foahvw0BVGyRk4htNOU9MU=,tag:rn4AMx091MNoBQOcS5o3Qg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: honcho-secrets
    namespace: hermes
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:XFZTF8ME6diJPn+hHsdSQHQ9E31j4luxjhkA8jioHv0=,iv:p5svKFON213Phah0oNjwzw3iZLmAPtHULwwF1MTbbXc=,tag:wGmUhRVHM2qpUOAsjUBDmQ==,type:str]
    db-connection-uri: ENC[AES256_GCM,data:X3OqsF/WH6oQRmBDIuRWrFAIfjDZHwUa5iN8/EZ5XjN+04Kjd8uix+Mr6/cxIZqpj2vOkWAW79LXeUO+3WpfJ6TjcAZB8RFtm9mE5mReXwxcXRArq0AbHw==,iv:pm7mudhWyNhwJGkUOx2P7lasgivOelt7BQs5A6+s/NA=,tag:1AS3wIxqZy0Y/StLlQbOcg==,type:str]
    opencode-go-api-key: ENC[AES256_GCM,data:eKmThAhgvWpTe90J4cjq6SV5o1+3GL2Dm3wECBPWnrkGlrhUSkUt0wlPe/lJug1OpHcm,iv:9/GYoV9rJy8LVW2gAHYmt4NlG85v1KpbtLIxZ+4I8eU=,tag:kq0HvlO2KsjSs7hcFcaF6Q==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:bvz69MQ7BswVUjFOUELhoVWYfxNuSBCGJiDjTvztv/MZSvocCVnyEXqtfIL7F8BvjevVNIy1j2c2TK1h20vCjGZE3L+7t7Rbhg==,iv:CguPdVg9qiaEAii/8nX3YVh6AmS9v6d5NtKwb4Gp53A=,tag:YcQCFwsRefbfvfQGltVXog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOazUzbW0ycmtFakN0azE2
            WTFUdXdhSGJxOERVMW1qbzR1eHpSZW9MR3djCklYb1JnOHhuNVUrVkh1S3p4REJX
            YjJiRWYrcG5naCtZWG1JazZ6VWJqaGsKLS0tIEs5T3dBcHJyUFh6cVZPMlR6UXZx
            M0EreXZtL2h3OEJaWEh1d0JweG1NWk0KQ+vJ9GbI51G7skHeI1aIgcGdIS6Nv4Ms
            K59JaZsKhJeKV/16H6wU5Hy4tTvrqx/f2oRu30rJUNbW63p4H3t3rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSDBHK2x2RVhaZFBjbkdL
            eUJOZDhUcDUrWDM5T1hlMGJnVlRQYmFSbEE0CkVobXdVelEwSWppOVJRd0diUG5i
            Yjc3cDg1ZGhnSkhUMTlsL001V01LTEUKLS0tIE5qWVk1czNLcEtoL1kwdDFVbzFI
            SG5TWXZENU1SRDNPY0twanF0Q2poYXMKxGqdKmbJLJFjdeh0PcuSAd8NjRg0i9Qa
            q4cWSZWHY249hkjkSUjnzB0EKCegUt2keJ6/LFifi0Rj1Ukiq67vBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa2RMcldpWTNJSHJsOFVS
            SUJxdzIySHhDb1VjRUxNUnZMNjZOWG1IVG1vCmI1MkVvWFdQMFN1OGczdUpqU3Js
            VERxQ1gxMUc5ekU4KytyaGZ5QmRPcFkKLS0tIHFpdmJKMW1Pak9ZUzlhY2NxTmt2
            YUpVbXE3UXhSemxJTVJ1bU9mUHFhZ3MKd5n1HOC6WhRz5zMworC8Jw/4+ZwM+KbO
            Kg9rAfNZ9SUv94oHU2IFO++4cFErW7xqKxY+W5pTUvEO4rQEduBddQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18c0ldwxzslhphke4gxaw2qgjdcpjp4d9dtzq8aew3sm7e383qpaq23607c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T00:26:56Z"
    mac: ENC[AES256_GCM,data:JLMc5/pzEzDyVmN7e1oV+5d/Y2b1lcMbpxCfvb/6LaifXrvzyAwqu2Qiyp1wLhuT6Hkwop2eNp3EH1dAZPTRsEMRMvEUVPHaAP/wM/OT9XwKAKPTzMBqh4PK2XeZBg1Wd7Xp5HtpXBu7EIIUQ6o0ZWvKP80o67spQk7rX4uYH5Q=,iv:tbs0GX54HG5POATBbZE87foahvw0BVGyRk4htNOU9MU=,tag:rn4AMx091MNoBQOcS5o3Qg==,type:str]
    version: 3.13.3
