apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    opencode-go-api-key: ENC[AES256_GCM,data:rn2aF4yypyGo6FNSSDiO3O87+ZtoP+zL8UZHzqicIDcIFvWAr8eHyYPSuRD7KIZm4YTgxgKBsjLAxj4DO5oF4wyNSw==,iv:3v8LZ6FyRkYb+Z0iAAx3MwrNbMwV7blnxSsPZIlIq+M=,tag:CQvyVMAYRpEfBN6hgcfuqA==,type:str]
    discord-bot-token: ENC[AES256_GCM,data:vM4rT6M1+GYjkRb5SD1shvpdbrDOz5628Bjs7Wgz0WdLzAHoFYJhX6Df8Lxcf6tUBGYHyGvd/FIdTDUYwoU99zDvkMi8AtDb,iv:LXDNqWWBkccMCdEYHIkYe/PvWNTEZbbgl5+RSzaCKK4=,tag:8kd6TNyQXvqFWFX2BHnKXw==,type:str]
    keenable-api-key: ENC[AES256_GCM,data:Auij7AR32vd+uEwaYflNBr2Q2YjcNjiScgmSwrn+4R0RWZJNj0uXmPxTiEufLrgEPCsZAINNQr1r38GZCjWzlYCvhtyf2O2yCIlbupYyf/g=,iv:8MTN5YVqoF3DEfmoZ24AbnTcxecdkqamqaTUzTdJ/tw=,tag:0BXk7bX7xvGes+uJb8NvBg==,type:str]
    dashboard-username: ENC[AES256_GCM,data:xj3ksXaE,iv:tbVsXTKxm56m46w2Igs5zb2epeFXa2ZVpcB855UuOQw=,tag:yCc3pLdEAXIBHiZ60uhM/g==,type:str]
    dashboard-password: ENC[AES256_GCM,data:F/1nd8Am,iv:Cl6q+L4WJWlcXWaer7avEFRT+e+4psDAruTI50XpunE=,tag:f18pawFtmXa7y307av9LzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cy8zMVhwdmZMdjd5WW8x
            N1lQVVcycXg0N3I0UmlMUzFNa1RzZTd0Nm1zCkk1b21RbWJXN0V5QTU1UnBEVnBL
            bXcxMG9GTGhBTVh6M0dzMm9WcUhrb28KLS0tIHAxVEpuYVBVSVljQ05YV05HU1lM
            dzg4eG9odGNwTUQyYTJGUlhJZC9CQ1EKxUMBwj5ZnghnytQqXpfQB5kHsintzfap
            8mt5NrwoslCTxAzMpJJsd+6Wms9TF8xR6+/XY4CHhhz0yCznqPtDHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUCtWdXRGcFhEUGpJYjky
            SThzMndxMzZ3Y1ZvM1pUaVpIRkRJYlNnZ0RJClVFNzBKNVlpSDFxajBGazNBNEdO
            WVh2Z3lXeDdMQ1V1anRoWC9yNEY2WjQKLS0tIFlMOU9DbXBPNU4wTTBwbUlhN21o
            ZWtucW5Vd1Vic25XZGxKdTJ1UHJBYmcKyqLqPR5yF1G0GK4xtTC4SnaVzXyRA+9O
            6N0cxtpKBNi2IWGBJqjqv4y3lZ4dqbVWvDah7D5Y+BITP5GC3Vx3NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaWRBQkZrSFhPK0Nsa0VS
            N1pOek82b3l0cC9hSTZ5bGtaWCtQTWpJRG5NCmNqc0JqSzFoNmVFaFBwNEJlV0V1
            WkIrZ1prUk4vTk8wTW9FcC93R2FZQkEKLS0tIHlYckpGT0haQU82L1Y4SVlDMU1t
            aDJoOXBSYmJPWlRpNk9va2owWWZwbmcKUpGXtgREnyXORmr1wp6AldvooDl7hZ66
            FEYQcjcOrFjrf6rGQUMpR1zQOpA0Xz6IU7cirXMekmzVE9mN1Vczbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18c0ldwxzslhphke4gxaw2qgjdcpjp4d9dtzq8aew3sm7e383qpaq23607c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T12:54:44Z"
    mac: ENC[AES256_GCM,data:0rmvr9NgqnMdMfTrrfc4sSsEboENoGX3dDi1ZGUTfUwjQDYmp1HCba+vJ4ngZoRFAktDy7mNp4ql8wwLZ6T0qY7iCtPcvfnT/5jKDZprWGOmkhSyyXCWafZ/shg5BYb4ZnJGY4meaHwRbpey6Kk5UtZJZ+akAPn4Eni+abZ9Nas=,iv:4PKNVPWwzm8shmFQzu0lJL7ijEnc1rTIY/Mp+rcWptw=,tag:lAsYoOkfvcvONfUQMw148Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: honcho-secrets
    namespace: hermes
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:sQKv1IPfqt/2fZOnSA9hhZTtYv9QjIk3T3sxAYYr22Q=,iv:HV1rbuU3g4DA6ObUKUppAgqkZMFWx+iQw1tCoy4a2lI=,tag:aaBuC69R/dkj3A2RMpTJnQ==,type:str]
    db-connection-uri: ENC[AES256_GCM,data:ncNxQTzCY/XrCqjQn/0/zpfLmQXUbM0abvWzXlqxPwcL+Axm0jw7QfuQUEesAfiGPKapgKsm6saptlyB5ctb6Om8Ud9wtAS6GT51REfSC0VlVaWYNy723w==,iv:b+KnsUOgjvoN4yt2jszn3SnnJbEVXLNqvM5SICv2TGw=,tag:/hGG32HHv4GBPEIB5sDgZA==,type:str]
    opencode-go-api-key: ENC[AES256_GCM,data:XSpDLTPSSCYynFt2/KY1vf2mTogxuRcaBENirEwmvI+Fsq+0yu/7OQBPw3hf3TLl6fsOtBP+/KINm3c7XXZlkilQnw==,iv:E2l3Ae5Jqurqm0k0doDdxaWSeYNQaG0CyfAZo+KOxxY=,tag:9AEtcB3ueKmQBFyFMXdXsA==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:QkicWyNVDCbS9cp1lD9lpEg02k6RmRg6Ru6p5cVfLdunZbWbi8gEB/ESI/CFBgU707xlrgxRwsCLVAMzwGyNIDtBnB1yYOLhWg==,iv:H0gOYsSlkd8qNzMRkTjNwvjb4aAMNsfj/TLrmlNbctg=,tag:xBynTRSVRg2UeOTp7gBAzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cy8zMVhwdmZMdjd5WW8x
            N1lQVVcycXg0N3I0UmlMUzFNa1RzZTd0Nm1zCkk1b21RbWJXN0V5QTU1UnBEVnBL
            bXcxMG9GTGhBTVh6M0dzMm9WcUhrb28KLS0tIHAxVEpuYVBVSVljQ05YV05HU1lM
            dzg4eG9odGNwTUQyYTJGUlhJZC9CQ1EKxUMBwj5ZnghnytQqXpfQB5kHsintzfap
            8mt5NrwoslCTxAzMpJJsd+6Wms9TF8xR6+/XY4CHhhz0yCznqPtDHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUCtWdXRGcFhEUGpJYjky
            SThzMndxMzZ3Y1ZvM1pUaVpIRkRJYlNnZ0RJClVFNzBKNVlpSDFxajBGazNBNEdO
            WVh2Z3lXeDdMQ1V1anRoWC9yNEY2WjQKLS0tIFlMOU9DbXBPNU4wTTBwbUlhN21o
            ZWtucW5Vd1Vic25XZGxKdTJ1UHJBYmcKyqLqPR5yF1G0GK4xtTC4SnaVzXyRA+9O
            6N0cxtpKBNi2IWGBJqjqv4y3lZ4dqbVWvDah7D5Y+BITP5GC3Vx3NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaWRBQkZrSFhPK0Nsa0VS
            N1pOek82b3l0cC9hSTZ5bGtaWCtQTWpJRG5NCmNqc0JqSzFoNmVFaFBwNEJlV0V1
            WkIrZ1prUk4vTk8wTW9FcC93R2FZQkEKLS0tIHlYckpGT0haQU82L1Y4SVlDMU1t
            aDJoOXBSYmJPWlRpNk9va2owWWZwbmcKUpGXtgREnyXORmr1wp6AldvooDl7hZ66
            FEYQcjcOrFjrf6rGQUMpR1zQOpA0Xz6IU7cirXMekmzVE9mN1Vczbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18c0ldwxzslhphke4gxaw2qgjdcpjp4d9dtzq8aew3sm7e383qpaq23607c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T12:54:44Z"
    mac: ENC[AES256_GCM,data:0rmvr9NgqnMdMfTrrfc4sSsEboENoGX3dDi1ZGUTfUwjQDYmp1HCba+vJ4ngZoRFAktDy7mNp4ql8wwLZ6T0qY7iCtPcvfnT/5jKDZprWGOmkhSyyXCWafZ/shg5BYb4ZnJGY4meaHwRbpey6Kk5UtZJZ+akAPn4Eni+abZ9Nas=,iv:4PKNVPWwzm8shmFQzu0lJL7ijEnc1rTIY/Mp+rcWptw=,tag:lAsYoOkfvcvONfUQMw148Q==,type:str]
    version: 3.13.3
