#!/usr/bin/env python3
"""ノード用ブートストラップスクリプトを生成する。

現地作業者が OS インストール後に1回実行するスクリプトを標準出力に出す。
実行するとノードが WireGuard spoke としてハブへ接続し、以降は管理者が
リモート(wg 経由 SSH)で Ansible を実行できるようになる。

使い方(管理者マシンで。sops と age 秘密鍵が必要):
    make node-bootstrap HOST=site1-node1
    # → bootstrap-site1-node1.sh が生成される(gitignore 対象)

注意:
- 生成物には wg 秘密鍵が平文で入る。安全な経路で渡し、実行後は削除させること
- 渡し方: 推測不能な URL に置いて、現地では
    curl -fsSL <URL> | sudo bash
  で実行させる(標準入力から読むので途中で切れても set -e で止まる。
  ファイルに落とさないので消し忘れも無い)。URL は実行後すぐ無効化すること
- wg0.conf の内容は ansible/roles/wireguard/templates/wg0.conf.j2 (spoke) と
  同等にしてある。初回の `make cluster` で Ansible が同じ内容で上書きするため、
  多少の乖離があっても一時的
"""

import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent


def load(path: str):
    return yaml.safe_load((ROOT / path).read_text())


def find_host(host: str):
    inv = load("ansible/inventory/hosts.yml")

    def walk(node: dict, site: str | None):
        for name, sub in (node.get("children") or {}).items():
            found = walk(sub or {}, name if name.startswith("site") and "_" not in name else site)
            if found:
                return found
        for name, hv in (node.get("hosts") or {}).items():
            if name == host:
                return (hv or {}), site
        return None

    found = walk(inv["all"], None)
    if not found:
        sys.exit(f"error: host {host} が inventory に無い")
    return found


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(f"usage: {sys.argv[0]} <host>  (例: site1-node1)")
    host = sys.argv[1]
    hv, site = find_host(host)
    if site is None:
        sys.exit(f"error: {host} は site 配下のノードではない(gateway には使えない)")

    net = load("ansible/group_vars/all/network.yml")
    sv = load(f"ansible/group_vars/{site}.yml")
    gw_pub = load("ansible/host_vars/linode-gw/main.yml")["wg_public_key"]
    if gw_pub == "REPLACE_WITH_REAL_PUBKEY":
        sys.exit("error: linode-gw の wg 公開鍵が未生成(make wg-keygen HOST=linode-gw)")

    dec = subprocess.run(
        ["sops", "-d", str(ROOT / f"ansible/host_vars/{host}/wireguard.sops.yml")],
        capture_output=True,
        text=True,
        check=True,
    )
    priv = yaml.safe_load(dec.stdout)["wg_private_key"]
    node_pub = load(f"ansible/host_vars/{host}/main.yml")["wg_public_key"]
    endpoint_host = net.get("gateway_fqdn") or net["gateway_public_ip"]

    # priority 200: Cilium が local テーブルのルールを pref 100 へ動かすので、それより後ろに置く
    exclude = [sv["cluster_lan_cidr"], net["pod_cidr"], net["service_cidr"]]
    post_up = "\n".join(f"PostUp   = ip rule add to {c} lookup main priority 200" for c in exclude)
    # wg-quick が付ける src_valid_mark=1 は Cilium の mark 付きパケットを martian にするので戻す
    post_up += "\nPostUp   = sysctl -q -w net.ipv4.conf.all.src_valid_mark=0"
    post_down = "\n".join(f"PostDown = ip rule del to {c} lookup main priority 200" for c in exclude)

    print(f"""#!/usr/bin/env bash
# Bootstrap script for {host} (generated by moripa-infra scripts/gen_node_bootstrap.py).
# This file contains a private key. Delete it right after running:
#   sudo bash <this file> && rm <this file>
set -euo pipefail
[ "$(id -u)" = 0 ] || {{ echo "Please run with sudo."; exit 1; }}
# Guard against running on the wrong machine: the hostname set during OS install must match
[ "$(hostname)" = "{host}" ] || {{ echo "NG: this script is for {host}, but this machine is $(hostname). Please contact the administrator."; exit 1; }}

export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y -q wireguard

# Catch transcription errors (e.g. a hand-typed key): the embedded private key must
# derive the public key registered on the hub for this host.
expected_pub="{node_pub}"
actual_pub=$(echo "{priv}" | wg pubkey)
if [ "$actual_pub" != "$expected_pub" ]; then
    echo "NG: the private key in this script does not match the public key registered for {host}."
    echo "    expected: $expected_pub"
    echo "    actual:   $actual_pub"
    echo "    The script was probably altered while copying. Re-run it exactly as provided (curl ... | sudo bash)."
    exit 1
fi

# systemd-networkd (Ubuntu's default) deletes routing policy rules and routes it did
# not create whenever it reconfigures a link. wg-quick's full tunnel relies on such a
# rule ("not fwmark ... lookup 51820"); without it, traffic for the hub leaves the LAN
# unencrypted and the tunnel looks up but nothing gets through. Keep them.
# (The cluster_lan Ansible role writes the same file later.)
if systemctl is-active --quiet systemd-networkd; then
    mkdir -p /etc/systemd/networkd.conf.d
    cat > /etc/systemd/networkd.conf.d/90-keep-wireguard.conf <<'NETEOF'
[Network]
ManageForeignRoutingPolicyRules=no
ManageForeignRoutes=no
NETEOF
    systemctl restart systemd-networkd
    sleep 2
fi

umask 077
cat > /etc/wireguard/wg0.conf <<'WGEOF'
[Interface]
Address    = {hv["wg_address"]}/32
PrivateKey = {priv}
MTU        = {net["wg_mtu"]}
{post_up}
{post_down}

[Peer]  # linode-gw (hub)
PublicKey           = {gw_pub}
Endpoint            = {endpoint_host}:{net["wg_port"]}
AllowedIPs          = 0.0.0.0/0
PersistentKeepalive = 25
WGEOF

# Restart (not just enable) so a re-run picks up a corrected config
systemctl enable wg-quick@wg0 > /dev/null 2>&1
systemctl restart wg-quick@wg0

echo "Checking connectivity to the hub (up to 30s)..."
ok=0
for _ in $(seq 1 10); do
    if ping -c 1 -W 3 {net["wg_hub_address"]} > /dev/null 2>&1; then ok=1; break; fi
done
if [ "$ok" = 1 ]; then
    echo "OK: Connected. On-site work is complete. Please contact the administrator."
    exit 0
fi

# ---- Diagnostics: printed only on failure. Send this whole output to the administrator.
echo "NG: Cannot reach the hub. Please send everything below to the administrator."
echo "===== diagnostics ====="
echo "hostname: $(hostname)"
echo "public key: $(wg show wg0 public-key 2>/dev/null || echo '(wg0 is not up)')  (expected: $expected_pub)"
echo "wg-quick@wg0: $(systemctl is-active wg-quick@wg0)"
hs=$(wg show wg0 latest-handshakes 2>/dev/null | awk '{{print $2}}')
if [ -z "$hs" ] || [ "$hs" = 0 ]; then
    echo "handshake: none  -> packets are not reaching the hub, or the hub does not know this key"
else
    echo "handshake: $(date -d @"$hs")  -> tunnel is up; the problem is routing or DNS"
fi
echo "transfer: $(wg show wg0 transfer 2>/dev/null | awk '{{print "rx="$2" tx="$3}}')"
echo "endpoint: {endpoint_host} -> $(getent ahostsv4 {endpoint_host} | awk 'NR==1{{print $1; f=1}} END{{if(!f) print "DNS FAILED"}}')"
echo "default route (main table): $(ip route show default | head -1)"
echo "addresses:"; ip -br addr | sed 's/^/    /'
echo "routes:"; ip route | sed 's/^/    /'
echo "rules:"; ip rule | sed 's/^/    /'
ip rule | grep -q 'not from all fwmark' || echo "    !! wg-quick's fwmark rule is missing -> the full tunnel is not routing (networkd removed it?)"
echo "table 51820:"; ip route show table 51820 2>/dev/null | sed 's/^/    /'
# With the full tunnel up, plain ping goes into wg0. Use the wg fwmark so the packet
# bypasses the tunnel and tests the LAN's own internet access.
mark=$(wg show wg0 fwmark 2>/dev/null | sed 's/^0x//'); mark=$((16#${{mark:-0}}))
echo "internet (bypassing wg0): $(ping -m "$mark" -c 1 -W 3 1.1.1.1 > /dev/null 2>&1 && echo reachable || echo UNREACHABLE)"
echo "hub endpoint (bypassing wg0): $(ping -m "$mark" -c 1 -W 3 {net["gateway_public_ip"]} > /dev/null 2>&1 && echo reachable || echo UNREACHABLE)"
echo "dns: $(getent hosts deb.debian.org > /dev/null 2>&1 && echo ok || echo FAILED)"
echo "clock: $(date -u +%Y-%m-%dT%H:%M:%SZ)  (a clock off by more than a few minutes breaks the handshake)"
echo "======================="
echo "Hints: no handshake + internet reachable => the router may block UDP {net["wg_port"]} outbound, or the hub has not registered this key yet."
echo "       internet UNREACHABLE or empty default route => the LAN link / DHCP is the problem; check the cable and 'ip -br addr'."
exit 1""")


if __name__ == "__main__":
    main()
