cloudflare_dns_api_token: ENC[AES256_GCM,data:Ilqs1R98uAHxKSsoNlHPT5c0DPxNIlEaWVUjQPcOAyirnoE0jUawx0tRVTsWnL9ypBNzy3M=,iv:P6fe2gKiJVfO+jw8tRBd5KpE1V3l9TWYtadCEUtZV/0=,tag:wEU9xgYcwrbMBLkoul5Kaw==,type:str]
oauth2_proxy_github_client_id: ENC[AES256_GCM,data:dmWhIuOzEZg5XMBjyL8vwK1M0z0=,iv:p2nEMgCkkGWbF5YOx/BcVuSbR1ZzpVuupPKFj/8v6Zw=,tag:iRDG1cBTbBJGRQ+pzEM+Pw==,type:str]
oauth2_proxy_github_client_secret: ENC[AES256_GCM,data:IzeinivcazTgTNPuYrAKsQQlnou1HXPwzYKmJrcFkZQyz/dY9k9wxA==,iv:99C0mfemapsD1snYlq3XBiYdJhTphQ6AeHGfVF1tg/c=,tag:G46rXXv3Y37Mu7pAeMZgqQ==,type:str]
oauth2_proxy_mineauth_client_id: ENC[AES256_GCM,data:qo5gfe5GHptegxdgChPQ1J0iKECLSeBhG/tjaQ2QY3QL5K7Z,iv:3xIVpa54Rj2qNYZakUsy0gFeVzbsTm+CJPR2YyKslO0=,tag:kjrv5p8PxBHwKuM3ilh6Og==,type:str]
oauth2_proxy_mineauth_client_secret: ENC[AES256_GCM,data:F9w6OtXJN/IzNvgC61DNVJkdIyuGSZe2OZLvrwCQSasUuKf9SCRK15jTow==,iv:A8yFV6C6w4cq+L0WLhgvwY1i+Gm6+Z0JkBPWRPx6ePM=,tag:CDjJKZvQHaEeBb+392EV+Q==,type:str]
oauth2_proxy_github_cookie_secret: ENC[AES256_GCM,data:1a5nW7D1WqI9KukQe9X5rq25UY4QjVzBstkQnMueeltbrtFBALNZcuxSEbQ=,iv:UXEW2w4F0/SRb2XKWfhkn23l8yEvakuaVD60ssUkfZ8=,tag:AniKZ1bIigkcIPrdasZfXg==,type:str]
oauth2_proxy_mineauth_cookie_secret: ENC[AES256_GCM,data:gdV+GxqNGZrHhv3APnAd78mYQ3SIqcttnUGYVLKUNFVdTiy8dgRitLfiDnc=,iv:sGzIxKEEqVFnRGDSS77w8ucmXq1KTGgd0ECzShFQvIk=,tag:piHMdnUGashSf1wIHf53tw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNUw5TVozYmcxc2dNSTBj
            dHdsTzloUEluUWZGTXNqU0V1SUM3SzlPRUNVClJxQ0cyTXhCWmE5ZUhGbmF4WTg3
            anYwamxjR3ZxY2QxYm9XaEV6UGV1VVEKLS0tIE93bmlZdkpyMWNEUkhqRmkrMFpF
            YXhNV3RvYTNZdnVYbjJYa2ZzUlRFQW8KngfoGvF9vk2E2o6grgYnS9k0ghFgBhzn
            aAcbb72dID3Qd9EECxehIwujyOwgcU2KjJhOB+LXplncevY2eeY/XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x2rhgwpnwekfdeppgm5wll9rzsdqr48n0vk8xla4thtm9wwrzaps7urd3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU1E3VTZlMThlZFYrV0M2
            NEdwMU5oMUN3L29NOWR3SXJ2SlJkeFlaZmlRCkJIaEVpZkozeG5aZERYN2pCYXRB
            bFpVTSsvejYvWTlGaml4amhtSTRXdTQKLS0tIG1tV0J6Ni9WVWZDTnU0QmZpTEZh
            cVN2MXRpamQvNDVsUzFLVzAvMk84R28K6ASUNsPIPO4GYzfUuKPpjk6JKDPhDMez
            qzhUdVd75QCC1yZGubgGVDwtIwF8EJulCZXMfcUpj5fr8sD8rdT4uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w488y6mddrsk48c505nf3rnufxgyyv8zx3qxj3x6st4saevlns5sn0v4qw
    lastmodified: "2026-09-09T16:56:50Z"
    mac: ENC[AES256_GCM,data:SBG2rKv+Ejl+R04EQK2BH29CEGx0rOsa6Ikn+joEq9zpQwhDbDy1t22e1oERvhXKg6hyI8ljGIyjNMrI7/jhllocnUujxfiOUSgogh3Jd5Vbwr/MUIKzakl0wEGu5hrtYi5DoXotBVj4c5oKhINzSHzes2S3SPY1VaMG9OIsNCM=,iv:1lts4mjnYW1GlYPY3bnzPNulOUdXaZhM7wcsEKHL8Ko=,tag:Gtg7L7HxoOPkD1Mb7FfRUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
